handle: stripeTest
isFrontendEnabled: true
name: 'Stripe Test'
paymentType: purchase
settings:
  apiKey: sk_test_51HuqgqDkOOyVTArnwXfHnWaEurOZGnI7JhmYXqYAiiBLEqQYPW4mt1xbOL3mnMHZjcPPEwV8jYgSqxlZEiA3uTAY00KncczEdb
  publishableKey: pk_test_51HuqgqDkOOyVTArn5Ee3uzHcHko2QKDIIK6xG3dXjiFxMQkaEHf1Y6mBQmFjZGazlfUvtV5sJ0vGZxzwmsDUFEB000FnXq3Be8
  sendReceiptEmail: ''
  signingSecret: whsec_JVnv2ct3nbMiEhv9epCLNhn3EDBozxPK
sortOrder: 99
type: craft\commerce\stripe\gateways\PaymentIntents
