{
    "orderId": 639,
    "orderData": {
        "number": "f28b16c3c8ee47c04a843fe1e7769f52",
        "reference": "f28b16c",
        "couponCode": null,
        "isCompleted": true,
        "dateOrdered": {
            "date": "12/15/2020",
            "time": "7:32 PM"
        },
        "datePaid": {
            "date": "12/15/2020",
            "time": "7:32 PM"
        },
        "dateAuthorized": null,
        "currency": "USD",
        "gatewayId": 1,
        "lastIp": "127.0.0.1",
        "message": null,
        "returnUrl": null,
        "cancelUrl": null,
        "orderStatusId": "1",
        "orderLanguage": "en-US",
        "orderSiteId": 1,
        "origin": "web",
        "billingAddressId": "3",
        "shippingAddressId": "3",
        "makePrimaryShippingAddress": null,
        "makePrimaryBillingAddress": null,
        "shippingSameAsBilling": null,
        "billingSameAsShipping": null,
        "estimatedBillingAddressId": null,
        "estimatedShippingAddressId": null,
        "estimatedBillingSameAsShipping": null,
        "shippingMethodHandle": "freeShipping",
        "shippingMethodName": "Free Shipping",
        "customerId": 1,
        "registerUserOnOrderComplete": null,
        "paymentSourceId": null,
        "storedTotalPrice": 98.950000000000003,
        "storedTotalPaid": 0,
        "storedItemTotal": 98.950000000000003,
        "storedItemSubtotal": 0,
        "storedTotalShippingCost": 0,
        "storedTotalDiscount": 0,
        "storedTotalTax": 0,
        "storedTotalTaxIncluded": 0,
        "id": 639,
        "tempId": null,
        "draftId": null,
        "revisionId": null,
        "uid": "cef50af0-9096-45b6-b466-87826e5731c5",
        "siteSettingsId": 639,
        "fieldLayoutId": 19,
        "contentId": 431,
        "enabled": true,
        "archived": false,
        "siteId": 1,
        "title": null,
        "slug": null,
        "uri": null,
        "dateCreated": {
            "date": "12/12/2020",
            "time": "1:46 AM"
        },
        "dateUpdated": {
            "date": "12/15/2020",
            "time": "7:32 PM"
        },
        "dateDeleted": null,
        "trashed": false,
        "propagateAll": false,
        "newSiteIds": [],
        "resaving": false,
        "duplicateOf": null,
        "previewing": false,
        "hardDelete": false,
        "ref": null,
        "status": "enabled",
        "structureId": null,
        "url": null,
        "eventContact": null,
        "eventPhone": null,
        "eventEmail": "jmayall@surething.com",
        "eventDate": {
            "date": "2020-12-14 00:00:00.000000",
            "timezone_type": 3,
            "timezone": "UTC"
        },
        "eventDayOfWeek": null,
        "eventTime": "5:00 PM",
        "eventMealTime": "7:00 PM",
        "eventOven": [
            {
                "label": "Is a working stove/oven available?",
                "value": "1",
                "selected": true,
                "valid": true
            },
            {
                "label": "Is a working stove/oven available?",
                "value": "1",
                "selected": true,
                "valid": true
            }
        ],
        "eventComments": "Testing the sending of an email when an order is placed",
        "fname": null,
        "adjustmentSubtotal": 0,
        "adjustmentsTotal": 0,
        "paymentCurrency": "USD",
        "email": "jmayall@surething.com",
        "isPaid": true,
        "itemSubtotal": 98.950000000000003,
        "itemTotal": 98.950000000000003,
        "lineItems": [
            {
                "id": 181,
                "weight": 0,
                "length": 0,
                "height": 0,
                "width": 0,
                "qty": 1,
                "note": "",
                "privateNote": "",
                "purchasableId": "430",
                "orderId": 639,
                "lineItemStatusId": null,
                "taxCategoryId": 1,
                "shippingCategoryId": 1,
                "dateCreated": "2020-12-15T19:30:25+00:00",
                "dateUpdated": "2020-12-15T19:32:34+00:00",
                "adjustments": [],
                "description": "Grilled Flat Iron",
                "options": [],
                "optionsSignature": "d751713988987e9331980363e24189ce",
                "onSale": false,
                "price": 34.950000000000003,
                "saleAmount": 0,
                "salePrice": 34.950000000000003,
                "sku": "grilled-flat-iron",
                "total": 34.950000000000003,
                "priceAsCurrency": "$34.95",
                "saleAmountAsCurrency": "$0.00",
                "salePriceAsCurrency": "$34.95",
                "subtotalAsCurrency": "$34.95",
                "totalAsCurrency": "$34.95",
                "discountAsCurrency": "$0.00",
                "shippingCostAsCurrency": "$0.00",
                "taxAsCurrency": "$0.00",
                "taxIncludedAsCurrency": "$0.00",
                "adjustmentsTotalAsCurrency": "$0.00",
                "subtotal": 34.950000000000003
            },
            {
                "id": 180,
                "weight": 0,
                "length": 0,
                "height": 0,
                "width": 0,
                "qty": 4,
                "note": "",
                "privateNote": "",
                "purchasableId": "428",
                "orderId": 639,
                "lineItemStatusId": null,
                "taxCategoryId": 1,
                "shippingCategoryId": 1,
                "dateCreated": "2020-12-12T01:46:25+00:00",
                "dateUpdated": "2020-12-15T19:32:34+00:00",
                "adjustments": [],
                "description": "Napa Chicken Sandwich",
                "options": [],
                "optionsSignature": "d751713988987e9331980363e24189ce",
                "onSale": false,
                "price": 16,
                "saleAmount": 0,
                "salePrice": 16,
                "sku": "napa-chicken-sandwich",
                "total": 64,
                "priceAsCurrency": "$16.00",
                "saleAmountAsCurrency": "$0.00",
                "salePriceAsCurrency": "$16.00",
                "subtotalAsCurrency": "$64.00",
                "totalAsCurrency": "$64.00",
                "discountAsCurrency": "$0.00",
                "shippingCostAsCurrency": "$0.00",
                "taxAsCurrency": "$0.00",
                "taxIncludedAsCurrency": "$0.00",
                "adjustmentsTotalAsCurrency": "$0.00",
                "subtotal": 64
            }
        ],
        "orderAdjustments": [],
        "outstandingBalance": 0,
        "paidStatus": "paid",
        "recalculationMode": "none",
        "shortNumber": "f28b16c",
        "totalPaid": 98.950000000000003,
        "total": 98.950000000000003,
        "totalPrice": 98.950000000000003,
        "totalQty": 5,
        "totalSaleAmount": 0,
        "totalTaxablePrice": 98.950000000000003,
        "totalWeight": 0,
        "adjustmentSubtotalAsCurrency": "$0.00",
        "adjustmentsTotalAsCurrency": "$0.00",
        "itemSubtotalAsCurrency": "$98.95",
        "itemTotalAsCurrency": "$98.95",
        "outstandingBalanceAsCurrency": "$0.00",
        "totalPaidAsCurrency": "$98.95",
        "totalAsCurrency": "$98.95",
        "totalPriceAsCurrency": "$98.95",
        "totalSaleAmountAsCurrency": "$0.00",
        "totalTaxablePriceAsCurrency": "$98.95",
        "totalTaxAsCurrency": "$0.00",
        "totalTaxIncludedAsCurrency": "$0.00",
        "totalShippingCostAsCurrency": "$0.00",
        "totalDiscountAsCurrency": "$0.00",
        "storedTotalPriceAsCurrency": "$98.95",
        "storedTotalPaidAsCurrency": "$0.00",
        "storedItemTotalAsCurrency": "$98.95",
        "storedItemSubtotalAsCurrency": "$0.00",
        "storedTotalShippingCostAsCurrency": "$0.00",
        "storedTotalDiscountAsCurrency": "$0.00",
        "storedTotalTaxAsCurrency": "$0.00",
        "storedTotalTaxIncludedAsCurrency": "$0.00",
        "paidStatusHtml": "<span class=\"commerceStatusLabel\"><span class=\"status green\"></span> Paid</span>",
        "customerLinkHtml": "<span><a href=\"https://demaggs.local/admin/commerce/customers/1\">jmayall@surething.com</a></span>",
        "orderStatusHtml": "<span class=\"commerceStatusLabel\"><span class=\"status green\"></span> New</span>",
        "totalTax": 0,
        "totalTaxIncluded": 0,
        "totalShippingCost": 0,
        "totalDiscount": 0
    },
    "commerceEmailId": "1",
    "orderHistoryId": 47,
    "description": null
}