bcc: null
cc: null
enabled: true
language: orderLanguage
name: 'Order Confirmation'
plainTextTemplatePath: ''
recipientType: customer
replyTo: info@demaggs.com
subject: 'Congratulations! Your Event with Demaggs Dining has been booked!'
templatePath: emails/confirmation
to: null
