field: a9e790af-96fa-43a2-a925-0e5d80b4c10b
fieldLayouts:
  465032c8-ca64-4a6f-a652-cd995173c9c0:
    tabs:
      -
        elements:
          -
            fieldUid: 425a1bea-9a6e-473a-bb8e-d5093fea1c3a
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b1f95553-0263-42e1-86c0-adfea1b4bea1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  425a1bea-9a6e-473a-bb8e-d5093fea1c3a:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: 'This field will not visible in the form, just in the source code'
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  b1f95553-0263-42e1-86c0-adfea1b4bea1:
    contentColumnType: text
    fieldGroup: null
    handle: hiddenValue
    instructions: 'You can use twig code'
    name: 'Hidden Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: '{{ craft.request.path }}'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: hidden
name: Hidden
sortOrder: 7
