field: a9e790af-96fa-43a2-a925-0e5d80b4c10b
fieldLayouts:
  df2091f1-d280-47d8-b74f-db938f8348ef:
    tabs:
      -
        elements:
          -
            fieldUid: 168473fd-885e-49e1-83bc-51c2af55c378
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5d7ad569-33bb-455c-9025-ce4f7604a387
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ec6b5422-36f8-44e5-a34a-f134ce528906
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e314b09e-9468-4f58-8e4c-fb030c5b5811
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6282200-9850-4081-a1f3-92b96d99f268
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  168473fd-885e-49e1-83bc-51c2af55c378:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  5d7ad569-33bb-455c-9025-ce4f7604a387:
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d6282200-9850-4081-a1f3-92b96d99f268:
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  e314b09e-9468-4f58-8e4c-fb030c5b5811:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: initialRows
    instructions: ''
    name: 'Initial Rows'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '2'
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  ec6b5422-36f8-44e5-a34a-f134ce528906:
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: ''
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 2
