field: a9e790af-96fa-43a2-a925-0e5d80b4c10b
fieldLayouts:
  11344c61-0262-4b60-9118-f06087c00d23:
    tabs:
      -
        elements:
          -
            fieldUid: 1a9bf9bc-dbe9-4148-9535-da9286ac7446
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0f8ead2f-70ed-4ad5-99cd-0db399669dda
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e6171c88-3920-4211-976f-1d82464d6c63
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 206843d8-9aa6-4a42-9d54-f5d8261790ef
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0f8ead2f-70ed-4ad5-99cd-0db399669dda:
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  1a9bf9bc-dbe9-4148-9535-da9286ac7446:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  206843d8-9aa6-4a42-9d54-f5d8261790ef:
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  e6171c88-3920-4211-976f-1d82464d6c63:
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: ''
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: singleLine
name: 'Single Line'
sortOrder: 1
