fieldLayouts:
  c2765edf-4998-46ef-b93b-d8703d2c7463:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 449edc88-393c-42de-a56e-c872495e6801
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 04e69910-2a20-4922-bf8d-34ac981b6fc9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c1c0c51f-346c-4019-b51c-4b7678647672
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f46ad1a8-5c82-4955-a279-ab97a11f1d63
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e93f8eb4-f749-4938-a656-941e5434a31b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Intro'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 08fe5ae7-e70b-4061-9cbb-e026d58fd0bc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: db41ab8d-9352-4b8c-9e47-d3ba26248fce
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8d042dc2-a4d8-4e41-830c-f3ad24854253
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 517586d5-61b3-4c3e-8e77-2657a2f8dbee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Contact Info'
        sortOrder: 3
handle: home
hasTitleField: true
name: 'Home Page'
section: e38ff358-652f-4c59-a771-87c4c9eab235
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
