fieldLayouts:
  611a647d-613d-4403-bad1-ba1626b4e2bd:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 770b2307-b4bd-4b4b-896d-5528dde9c707
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1765cca0-5152-4419-bfa4-1cae67885027
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: foodGroups
name: 'Food Groups'
siteSettings:
  6671a41b-84cc-4d94-91a7-02d6825a057c:
    hasUrls: true
    template: menu/category.twig
    uriFormat: 'menu/{slug}'
structure:
  maxLevels: 1
  uid: 1a2894de-367b-4417-a9bc-51c09569e4ca
