contentColumnType: datetime
fieldGroup: 046e05e8-3ec3-4c53-9775-11b9a4aa98d0
handle: eventDate
instructions: ''
name: 'Event Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
