contentColumnType: string
fieldGroup: 87d83a42-f702-4e0a-af18-b58a2a805d63
handle: partyType
instructions: ''
name: 'Party Type'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Intimate
        -
          - value
          - intimate
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - small
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - medium
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - large
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
