contentColumnType: text
fieldGroup: 0636a309-73dd-49bf-a3cb-5d3430ae582e
handle: phone
instructions: ''
name: Phone
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
