contentColumnType: string
fieldGroup: 6626cc62-17e2-4369-ae94-3025bab9933b
handle: specialsMatrix
instructions: ''
name: 'Specials Matrix'
searchable: false
settings:
  contentTable: '{{%matrixcontent_specialsmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
