dateModified: 1608381679
email:
  fromEmail: jmayall@surething.com
  fromName: 'Demaggs Dining'
  replyToEmail: jmayall@surething.com
  template: _emails/test
  transportSettings:
    apiKey: d2bb89bcc1ea72f352801914471f7e5a-e5da0167-aa75a5d1
    domain: mg.demaggs.com
    endpoint: 'https://api.mailgun.net'
  transportType: craft\mailgun\MailgunAdapter
plugins:
  commerce:
    edition: pro
    enabled: true
    schemaVersion: 3.2.13
  contact-form:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  freeform:
    edition: pro
    enabled: true
    schemaVersion: 3.1.0
    settings:
      ajaxByDefault: '1'
      alertNotificationRecipients: null
      autoScrollToErrors: '1'
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: '1'
      defaultView: submissions
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: ''
      footerScripts: false
      formSubmitDisable: ''
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: '1'
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: Freeform
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: '0'
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      removeNewlines: ''
      renderFormHtmlInCpViews: '1'
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: ''
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sprout-encode-email:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: demaggs
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: UTC
