dateModified: 1605210554
email:
  fromEmail: jmayall@surething.com
  fromName: 'Demaggs Dining'
  replyToEmail: jmayall@surething.com
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  commerce:
    edition: pro
    enabled: true
    schemaVersion: 3.2.9
  contact-form:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sprout-encode-email:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: demaggs
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
