fieldLayouts:
  34cadc68-c16c-4099-b42d-5d287c6ddf23:
    tabs:
      -
        elements:
          -
            fieldUid: 06024b66-e536-41c9-bc7f-d02ac0c55eaf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3fb74742-10d1-45ac-a373-20aee3bc1af5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e9e70d02-c2a0-41a4-9a12-7bac858f2299
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 18bd7420-14ec-48d9-8a95-90359532292a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d8db08f-2652-40d2-b4ea-1ed5a73cd674
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1d5ac3a8-1e33-446a-99dc-97ffe1243bd5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb487586-cf15-40bb-b653-0a2cc1f5ec2f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0881723-a5b5-42aa-821a-1c147bacc8fa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57451df3-7c82-40f1-a89e-45ccc1b53f0e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 45ec252f-e2d9-4b3e-95cc-29eeba6b77f5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b883ff7-b21b-44dd-8cc7-a70f84e8cbed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: cartVars
name: 'Cart Vars'
