fieldLayouts:
  0fb31bf8-7287-41ad-a167-8a8d6e78ee1d:
    tabs:
      -
        elements:
          -
            fieldUid: f9a7986c-608d-4bac-8352-19dc83b54628
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d4ac1c73-67de-41be-b213-36782b79cb17
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 31346aee-8fd3-46ab-99e4-329f13e03b09
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fd3f0462-d06a-4485-b381-957d6a8e5678
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f59f15a4-8aa7-41bb-a80e-7262ab08be6e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc651002-b776-465c-9c37-d35489fbf3d6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0eaad8c1-2c5f-4fd5-9826-f3b6eb93591d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bd55e07e-a3d0-4210-9132-e62d1bf78ee2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6faa4c1-d285-41d7-85e4-72b7b672ae5e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 87531e37-683c-49ce-9eba-1fd9b61749eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9022d78-cb67-49e8-948c-810513f6c1aa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 10565bb4-2c63-4bdd-bbbc-5fe96fa97740
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 313f6adb-f0fb-4488-86d5-f9feec216766
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Event Variables'
        sortOrder: 1
handle: events
name: 'Event Labels'
