fieldLayouts:
  bbcf9764-3e20-4e73-8e4e-ca56819b9c0c:
    tabs:
      -
        elements:
          -
            fieldUid: 43701e8d-5a3f-4814-a561-3548c8cbb835
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6097bdb-7a29-47d3-a3ec-08c794858f59
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 04404781-9234-4f84-ae9f-34c605b83d4f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4a46f319-d344-4513-bc42-4c77c5bc53f1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1d65ae94-14e1-491e-8e6b-3dc4d8714514
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 37023959-24b8-46df-bd83-ea8954107e54
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e154e391-5952-4fbf-bb15-f7c47e58a7c5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c913393b-a2ec-4d0a-8294-8aa29c269a17
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Vars
        sortOrder: 1
handle: globalVars
name: 'Global Vars'
