enableVersioning: true
handle: home
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - ''
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6671a41b-84cc-4d94-91a7-02d6825a057c:
    enabledByDefault: true
    hasUrls: true
    template: home-page/_entry
    uriFormat: __home__
type: single
