enableVersioning: true
handle: mobileMenu
name: 'Mobile Menu'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6671a41b-84cc-4d94-91a7-02d6825a057c:
    enabledByDefault: true
    hasUrls: true
    template: singles/mobileMenu
    uriFormat: mobileMenu
type: single
